<table class="table0001" align="center" width="900">
			<tr>
				<td align="center">
				<a href="index.php"><button class="button"><text class="menubar">Home</text></button></a>	
				</td>
				<td align="center">
				<a href="results.php"><button class="button"><text class="menubar">Results</text></button></a>	
				</td>
				<td align="center">
				<a href="winners.php"><button class="button"><text class="menubar">Winners</text></button></a>	
				</td>
				<td align="center">
				<a href="banking.php"><button class="button"><text class="menubar">Banking</text></button></a>	
				</td>
				<td align="center">
				<a href="<?php echo $this->globalPath; ?>support/index"><button class="button"><text class="menubar">Support</text></button></a>	
				</td>
				<td align="center">
				<a href="signup.php"><button class="button"><text class="menubar">Sign Up</text></button></a>	
				</td>
			</tr>
</table>
<table class="indextable" align="center">