<div class="logo"> </div><!-- MILLENIUM PLAY LOGO -->
	
	<div class="facebook"><!-- Follow us on Facebook -->
	<a target="http://www.facebook.com" href="http://www.facebook.com"><img src="<?php echo$this->globalProjectPath; ?>css/images/followus/facebook.png"/></a>
	</div>
	<div class="twitter"><!-- Follow us on Twitter -->
	<a target="http://www.twitter.com" href="http://www.twitter.com"><img src="<?php echo $this->globalProjectPath; ?>css/images/followus/twitter.png"/></a>
	</div>
	<div class="googleplus"><!-- Follow us on Google Plus -->
	<a target="http://www.plus.google.com" href="http://www.plus.google.com"><img src="<?php echo $this->globalProjectPath; ?>css/images/followus/googleplus.png"/></a>
	</div>
<table class="mainmenu" align="center" width="900">
			<tr>
				<td align="center">
				<a href="index.php"><button class="button"><text class="menubar">Home</text></button></a>	
				</td>
				<td align="center">
				<a href="results.php"><button class="button"><text class="menubar">Results</text></button></a>	
				</td>
				<td align="center">
				<a href="winners.php"><button class="button"><text class="menubar">Winners</text></button></a>	
				</td>
				<td align="center">
				<a href="banking.php"><button class="button"><text class="menubar">Banking</text></button></a>	
				</td>
				<td align="center">
				<a href="<?php echo $this->globalPath; ?>support/index"><button class="button"><text class="menubar">Support</text></button></a>	
				</td>
				<td align="center">
				<a href="signup.php"><button class="button"><text class="menubar">Sign Up</text></button></a>	
				</td>
			</tr>
</table>
