	<body>
	<?php echo $this->action('index', 'login'); ?>
	<?php echo $this->action('index', 'menu'); ?>
	
	<tr>
	<th>
		<table class="winnr" align="center">
			<tr>
				<td align="center">
					<div class="image">
					<img alt="" src="nr/ball01.png" />
					<div class="text">
					<p>10</p>
					</div>
					</div>
					
					
				</td>	
			</tr>
		</table>
		
	</th>
	</tr>
	</body>
	<?php echo $this->action('footer','index'); ?>
</html>