<table class="logotable" align="center">
		<tr>
			<td>
			<table class="logintable" align="right" cellspacing="0">
			<form name="SubmitLogin" action="login.php" onsubmit="return validateForm()" method="post">
				<tr>
				<td><p class="login">Username:</p></td>
				<td><input type="text" name="username" /></td>
				</tr>
				<tr>
				<td><p class="login">Password:</p></td>
				<td><input type="password" name="password" /></td>
				</tr>
				<th colspan="2">
				<input type="submit" class="buttonlogin" name="login" value="Log In"/>
			</form>
			
				<a href="lostpwd.php"><text class="login">Forgot Password?</text></a>				
				</th>
			</table>
			</td>
		</tr>
</table>