<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <META NAME="keywords" CONTENT="milleniumplay,online lottery,online gambling,online bingo,making money online" />
  <title>Welcome to Millenium Play</title>
  <?php echo $this->headLink()->appendStylesheet( $this->baseUrl() . '/' . '../css/global.css') ?>
</head>
<body>
<?php echo $this->layout()->content ?>
</body>
</html>